# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    displayName: "Dockerizing API"
    inputs:
      containerRegistry: "DockerHub"
      repository: "karcagtamas/papyrus"
      command: "buildAndPush"
      Dockerfile: "./Dockerfile"
      buildContext: "."
      tags: "latest"
  - task: Docker@2
    displayName: "Dockerizing Client"
    inputs:
      containerRegistry: "DockerHub"
      repository: "karcagtamas/papyrus_client"
      command: "buildAndPush"
      Dockerfile: "./Dockerfile.Client"
      buildContext: "."
      tags: "latest"
