// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Papyrus.DataAccess;

#nullable disable

namespace Papyrus.Migrations
{
    [DbContext(typeof(PapyrusContext))]
    [Migration("20221030194124_GroupRemoveLog")]
    partial class GroupRemoveLog
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.ActionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PerformerId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Segment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PerformerId");

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.AppAccess", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppAccesses");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Editor.EditorMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConnectionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoteId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasAlternateKey("UserId", "NoteId", "ConnectionId");

                    b.HasIndex("NoteId");

                    b.ToTable("EditorMembers");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Groups.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Groups.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AddedById")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasAlternateKey("GroupId", "UserId");

                    b.HasIndex("AddedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Groups.GroupRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("DeleteNote")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EditMemberList")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EditNote")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EditRoleList")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EditTagList")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("GroupEdit")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("ReadGroupActionLog")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReadMemberList")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReadNote")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReadNoteActionLog")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReadNoteList")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReadRoleList")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ReadTagList")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasAlternateKey("GroupId", "Name");

                    b.ToTable("GroupRoles");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "English",
                            ShortName = "en-US"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hungarian",
                            ShortName = "hu-HU"
                        });
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.Folder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("ParentId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Folders");

                    b.HasCheckConstraint("CK_Folder_Owner", "(GroupId IS NOT NULL OR UserId IS NOT NULL) AND NOT (GroupId IS NOT NULL AND UserId IS NOT NULL)");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.Note", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Archived")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ContentId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ContentLastEdit")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastUpdaterId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Public")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("FolderId");

                    b.HasIndex("GroupId");

                    b.HasIndex("LastUpdaterId");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");

                    b.HasCheckConstraint("CK_Note_Owner", "(GroupId IS NOT NULL OR UserId IS NOT NULL) AND NOT (GroupId IS NOT NULL AND UserId IS NOT NULL)");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.NoteAccess", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NoteId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NoteId");

                    b.HasIndex("UserId");

                    b.ToTable("NoteAccesses");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.NoteTag", b =>
                {
                    b.Property<string>("NoteId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("NoteId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("NoteTags");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("ParentId");

                    b.HasIndex("UserId");

                    b.ToTable("Tags");

                    b.HasCheckConstraint("CK_Tag_Owner", "(GroupId IS NOT NULL OR UserId IS NOT NULL) AND NOT (GroupId IS NOT NULL AND UserId IS NOT NULL)");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatorId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastUpdaterId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("LastUpdaterId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Translation", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Segment")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Language")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Key", "Segment", "Language");

                    b.ToTable("Translations");

                    b.HasData(
                        new
                        {
                            Key = "Administrator",
                            Segment = "Role",
                            Language = "en-US",
                            Value = "Administrator"
                        },
                        new
                        {
                            Key = "Administrator",
                            Segment = "Role",
                            Language = "hu-HU",
                            Value = "Adminisztrátor"
                        },
                        new
                        {
                            Key = "Moderator",
                            Segment = "Role",
                            Language = "en-US",
                            Value = "Moderator"
                        },
                        new
                        {
                            Key = "Moderator",
                            Segment = "Role",
                            Language = "hu-HU",
                            Value = "Moderátor"
                        },
                        new
                        {
                            Key = "User",
                            Segment = "Role",
                            Language = "en-US",
                            Value = "User"
                        },
                        new
                        {
                            Key = "User",
                            Segment = "Role",
                            Language = "hu-HU",
                            Value = "Felhasználó"
                        },
                        new
                        {
                            Key = "English",
                            Segment = "Language",
                            Language = "en-US",
                            Value = "English"
                        },
                        new
                        {
                            Key = "English",
                            Segment = "Language",
                            Language = "hu-HU",
                            Value = "Angol"
                        },
                        new
                        {
                            Key = "Hungarian",
                            Segment = "Language",
                            Language = "en-US",
                            Value = "Hungarian"
                        },
                        new
                        {
                            Key = "Hungarian",
                            Segment = "Language",
                            Language = "hu-HU",
                            Value = "Magyar"
                        },
                        new
                        {
                            Key = "Administrator",
                            Segment = "GroupRole",
                            Language = "en-US",
                            Value = "Administrator"
                        },
                        new
                        {
                            Key = "Administrator",
                            Segment = "GroupRole",
                            Language = "hu-HU",
                            Value = "Adminisztrátor"
                        },
                        new
                        {
                            Key = "Moderator",
                            Segment = "GroupRole",
                            Language = "en-US",
                            Value = "Moderator"
                        },
                        new
                        {
                            Key = "Moderator",
                            Segment = "GroupRole",
                            Language = "hu-HU",
                            Value = "Moderátor"
                        },
                        new
                        {
                            Key = "Default",
                            Segment = "GroupRole",
                            Language = "en-US",
                            Value = "Default"
                        },
                        new
                        {
                            Key = "Default",
                            Segment = "GroupRole",
                            Language = "hu-HU",
                            Value = "Alapértelmezett"
                        },
                        new
                        {
                            Key = "Create",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Created"
                        },
                        new
                        {
                            Key = "Create",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Csoport létrehozva"
                        },
                        new
                        {
                            Key = "Close",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Closed"
                        },
                        new
                        {
                            Key = "Close",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Csoport lezárva"
                        },
                        new
                        {
                            Key = "Open",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Opened"
                        },
                        new
                        {
                            Key = "Open",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Csoport kinyitva"
                        },
                        new
                        {
                            Key = "RoleCreate",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Role is created"
                        },
                        new
                        {
                            Key = "RoleCreate",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Szerepkör létrehozva"
                        },
                        new
                        {
                            Key = "RoleEdit",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Role is edited"
                        },
                        new
                        {
                            Key = "RoleEdit",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Szerepkör szerkesztve"
                        },
                        new
                        {
                            Key = "RoleRemove",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Role is removed"
                        },
                        new
                        {
                            Key = "RoleRemove",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Szerepkör törölve"
                        },
                        new
                        {
                            Key = "MemberAdd",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Member is added"
                        },
                        new
                        {
                            Key = "MemberAdd",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Tag hozzáadva"
                        },
                        new
                        {
                            Key = "MemberEdit",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Member is edited"
                        },
                        new
                        {
                            Key = "MemberEdit",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Tag szerkesztve"
                        },
                        new
                        {
                            Key = "MemberRemove",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Member is removed"
                        },
                        new
                        {
                            Key = "MemberRemove",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Tag törölve"
                        },
                        new
                        {
                            Key = "TagCreate",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Tag is created"
                        },
                        new
                        {
                            Key = "TagCreate",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Címke létrehozva"
                        },
                        new
                        {
                            Key = "TagEdite",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Tag is edited"
                        },
                        new
                        {
                            Key = "TagEdite",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Címke szerkesztve"
                        },
                        new
                        {
                            Key = "TagRemove",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Tag is removed"
                        },
                        new
                        {
                            Key = "TagRemove",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Címke törölve"
                        },
                        new
                        {
                            Key = "DataEdit",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Data is edited"
                        },
                        new
                        {
                            Key = "DataEdit",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Adatok szerkesztve"
                        },
                        new
                        {
                            Key = "NoteCreate",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Note is created"
                        },
                        new
                        {
                            Key = "NoteCreate",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Jegyzet létrehozva"
                        },
                        new
                        {
                            Key = "Remove",
                            Segment = "Group",
                            Language = "en-US",
                            Value = "Group is removed"
                        },
                        new
                        {
                            Key = "Remove",
                            Segment = "Group",
                            Language = "hu-HU",
                            Value = "Csoport törölve"
                        },
                        new
                        {
                            Key = "Create",
                            Segment = "Note",
                            Language = "en-US",
                            Value = "Created"
                        },
                        new
                        {
                            Key = "Create",
                            Segment = "Note",
                            Language = "hu-HU",
                            Value = "Létrehozva"
                        },
                        new
                        {
                            Key = "TitleEdit",
                            Segment = "Note",
                            Language = "en-US",
                            Value = "Title is edited"
                        },
                        new
                        {
                            Key = "TitleEdit",
                            Segment = "Note",
                            Language = "hu-HU",
                            Value = "Cím szerkesztve"
                        },
                        new
                        {
                            Key = "ContentEdit",
                            Segment = "Note",
                            Language = "en-US",
                            Value = "Content is edited"
                        },
                        new
                        {
                            Key = "ContentEdit",
                            Segment = "Note",
                            Language = "hu-HU",
                            Value = "Tartalom szerkesztve"
                        },
                        new
                        {
                            Key = "TagEdit",
                            Segment = "Note",
                            Language = "en-US",
                            Value = "Tag(s) added or removed"
                        },
                        new
                        {
                            Key = "TagEdit",
                            Segment = "Note",
                            Language = "hu-HU",
                            Value = "Címke/Címkék hozzáadva vagy törölve"
                        },
                        new
                        {
                            Key = "Delete",
                            Segment = "Note",
                            Language = "en-US",
                            Value = "Deleted"
                        },
                        new
                        {
                            Key = "Delete",
                            Segment = "Note",
                            Language = "hu-HU",
                            Value = "Törölve"
                        },
                        new
                        {
                            Key = "Publish",
                            Segment = "Note",
                            Language = "en-US",
                            Value = "Public status is changed"
                        },
                        new
                        {
                            Key = "Publish",
                            Segment = "Note",
                            Language = "hu-HU",
                            Value = "Nyílvános státusz megváltoztatva"
                        },
                        new
                        {
                            Key = "Archived",
                            Segment = "Note",
                            Language = "en-US",
                            Value = "Archived status is changed"
                        },
                        new
                        {
                            Key = "Archived",
                            Segment = "Note",
                            Language = "hu-HU",
                            Value = "Archivált státusz megváltoztatva"
                        },
                        new
                        {
                            Key = "0",
                            Segment = "Theme",
                            Language = "en-US",
                            Value = "Light Theme"
                        },
                        new
                        {
                            Key = "0",
                            Segment = "Theme",
                            Language = "hu-HU",
                            Value = "Világos Téma"
                        },
                        new
                        {
                            Key = "1",
                            Segment = "Theme",
                            Language = "en-US",
                            Value = "Dark Theme"
                        },
                        new
                        {
                            Key = "1",
                            Segment = "Theme",
                            Language = "hu-HU",
                            Value = "Sötét Téma"
                        });
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<bool>("Disabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImageId")
                        .HasColumnType("longtext");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastOsirisSync")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("OsirisId")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Registration")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int>("Theme")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LanguageId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.Role", null)
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papyrus.DataAccess.Entities.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.ActionLog", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.User", "Performer")
                        .WithMany("ActionLogs")
                        .HasForeignKey("PerformerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Performer");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.AppAccess", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.User", "User")
                        .WithMany("AppAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Editor.EditorMember", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.Notes.Note", "Note")
                        .WithMany("EditorMemberships")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papyrus.DataAccess.Entities.User", "User")
                        .WithMany("EditorMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Groups.Group", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.User", "Owner")
                        .WithMany("CreatedGroups")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Groups.GroupMember", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.User", "AddedBy")
                        .WithMany("AddedGroupMembers")
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Papyrus.DataAccess.Entities.Groups.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papyrus.DataAccess.Entities.Groups.GroupRole", "Role")
                        .WithMany("Members")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Papyrus.DataAccess.Entities.User", "User")
                        .WithMany("Groups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("Group");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Groups.GroupRole", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.Groups.Group", "Group")
                        .WithMany("Roles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.Folder", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.User", "Creator")
                        .WithMany("CreatedFolders")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Papyrus.DataAccess.Entities.Groups.Group", "Group")
                        .WithMany("Folders")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Papyrus.DataAccess.Entities.Notes.Folder", "Parent")
                        .WithMany("Folders")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Papyrus.DataAccess.Entities.User", "User")
                        .WithMany("Folders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Creator");

                    b.Navigation("Group");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.Note", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.User", "Creator")
                        .WithMany("CreatedNotes")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Papyrus.DataAccess.Entities.Notes.Folder", "Folder")
                        .WithMany("Notes")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papyrus.DataAccess.Entities.Groups.Group", "Group")
                        .WithMany("Notes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Papyrus.DataAccess.Entities.User", "LastUpdater")
                        .WithMany("LastUpdatedNotes")
                        .HasForeignKey("LastUpdaterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Papyrus.DataAccess.Entities.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Creator");

                    b.Navigation("Folder");

                    b.Navigation("Group");

                    b.Navigation("LastUpdater");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.NoteAccess", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.Notes.Note", "Note")
                        .WithMany("Accesses")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papyrus.DataAccess.Entities.User", "User")
                        .WithMany("NoteAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.NoteTag", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.Notes.Note", "Note")
                        .WithMany("Tags")
                        .HasForeignKey("NoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Papyrus.DataAccess.Entities.Notes.Tag", "Tag")
                        .WithMany("Notes")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.Tag", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.Groups.Group", "Group")
                        .WithMany("Tags")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Papyrus.DataAccess.Entities.Notes.Tag", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Papyrus.DataAccess.Entities.User", "User")
                        .WithMany("Tags")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Group");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Post", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.User", "Creator")
                        .WithMany("CreatedPosts")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Papyrus.DataAccess.Entities.User", "LastUpdater")
                        .WithMany("UpdatedPosts")
                        .HasForeignKey("LastUpdaterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");

                    b.Navigation("LastUpdater");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.RefreshToken", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.User", b =>
                {
                    b.HasOne("Papyrus.DataAccess.Entities.Language", "Language")
                        .WithMany("Users")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Groups.Group", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("Members");

                    b.Navigation("Notes");

                    b.Navigation("Roles");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Groups.GroupRole", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Language", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.Folder", b =>
                {
                    b.Navigation("Folders");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.Note", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("EditorMemberships");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Notes.Tag", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Papyrus.DataAccess.Entities.User", b =>
                {
                    b.Navigation("ActionLogs");

                    b.Navigation("AddedGroupMembers");

                    b.Navigation("AppAccesses");

                    b.Navigation("CreatedFolders");

                    b.Navigation("CreatedGroups");

                    b.Navigation("CreatedNotes");

                    b.Navigation("CreatedPosts");

                    b.Navigation("EditorMemberships");

                    b.Navigation("Folders");

                    b.Navigation("Groups");

                    b.Navigation("LastUpdatedNotes");

                    b.Navigation("NoteAccesses");

                    b.Navigation("Notes");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");

                    b.Navigation("Tags");

                    b.Navigation("UpdatedPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
